dp.add_handler(CommandHandler('tagall', tagall))
dp.add_handler(CommandHandler('makeadmin', makeadmin, pass_args=True))
dp.add_handler(CommandHandler('adduser', adduser, pass_args=True))
dp.add_handler(CommandHandler('kick', kick, pass_args=True))
dp.add_handler(CommandHandler('mute', mute))
dp.add_handler(CommandHandler('ban', ban, pass_args=True))
dp.add_handler(CommandHandle_r('generate_image', generate_image, pass_args=True))
dp.add_handler(CommandHandler('block', block, pass_args=True))
dp.add_handler(CommandHandler('unblock', unblock, pass_args=True))
dp.add_handler(CommandHandler('creategroup', creategroup, pass_args=True))
dp.add_handler(CommandHandler('fun', fun))
dp.add_handler(CommandHandler('joke', joke))
dp.add_handler(CommandHandler('meme', meme))
dp.add_handler(CommandHandler('games', games))
dp.add_handler(CommandHandler('tictactoe', tictactoe))
dp.add_handler(CommandHandler('wcg', wcg))
dp.add_handler(CommandHandler('motivation', motivation))
dp.add_handler(CommandHandler('advice', advice, pass_args=True))
dp.add_handler(CommandHandler('download', download, pass_args=True))
dp.add_handler(CommandHandler('ping', ping))
dp.add_handler(CommandHandler('runtime', runtime))
dp.add_handler(CommandHandler('users', users))
dp.add_handler(CommandHandler('panel', panel))
dp.add_handler(CommandHandler('alive', ping))
dp.add_handler(CommandHandler('math', math, pass_args=True))
dp.add_handler(CommandHandler('essay', essay, pass_args=True))
dp.add_handler(CommandHandler('event', event, pass_args=True))
dp.add_handler(CommandHandler('start_reminder', start_reminder))
dp.add_handler(CommandHandler('google', google_search, pass_args=True))